id: IC4AFF292
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T05:26:13+00:00'
last_modified: '2022-06-08T09:27:58.579224+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ6600
  title: རྡོ་རིང་པཎ་ཆེན་གྱི་དག་སྣང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    459E:
      image_group_id: I1KG1415
      title: ''
      total_pages: 96
      order: 1
      base_file: 459E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
